services:
  fastapi: &fastapi
    profiles: [ "prod" ]
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql+psycopg://admin:password@localhost:5432/db_dev
    command:
      - bash
      - -c
      - |
        python3 -m alembic upgrade head
        python3 -m gunicorn app.main:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker -w 8
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=db_dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
